# Copyright (C) 2017 Peter Robinson
# Docker file used for creating run-time docker image.
# Use a minimalist base image.
FROM busybox
MAINTAINER Peter Robinson <peter@nelladragon.com>

# Put in the settings file needed at runtime.
RUN mkdir /etc/gateway
ADD settings.json /etc/gateway

# Add the binary
ADD gateway /

# Run the binary when the container starts.
WORKDIR /
CMD ["/gateway"]
EXPOSE 8080 
